services:
  # PHP-FPM Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    environment:
      - DB_HOST=mysql # Meaning that's running on localhost
      - DB_PORT=3306
      - DB_DATABASE=simple_php
      - DB_USERNAME=root
      - DB_PASSWORD=root_password

  # Nginx Service
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks:
      - app-network

  # MySQL Service
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    restart: always
    ports:
      - "33060:3306"  # Changed from 3306:3306 to avoid port conflicts
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: simple_php
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    restart: always
    ports:
      - "8081:80"  # Changed from 8081:80 to avoid port conflicts
    environment:
      PMA_HOST: mysql # Meaning that's running on localhost
      PMA_USER: root
      PMA_PASSWORD: root_password
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: